services:
  db:
    image: postgres:10.7-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=dejavu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  app:
    image: YOUR_DEJAVU_IMAGE
    depends_on:
      - db